[package]
name = "ic_bench"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Measure primary key reads and writes, one thread, asynchronous batches"

[lints]
workspace = true

[dependencies]
ic_port.workspace = true
ic_util.workspace = true
ic_apic.workspace = true
ic_apid.workspace = true
ic_ndb_signals.workspace = true
