// Copyright (c) 2026 Hopsworks and/or its affiliates.
// Licensed under the MIT License. See LICENSE in the repository root.

//! `ic_capi`: the C ABI of iClaustron, built as `libiclaustron`.
//!
//! Every public method of `ic_apid` gets one exported `ic_*` function
//! here; all types crossing the boundary are `#[repr(C)]` or opaque. The
//! header `include/iclaustron/ic_apid.h` is hand-written in Phase 0 as the
//! design artefact and generated by `cbindgen` from this crate in Phase 7.
//!
//! Phase 0: only the version function exists.

/// Major version of the C API.
pub const IC_API_VERSION_MAJOR: u32 = 0;
/// Minor version of the C API.
pub const IC_API_VERSION_MINOR: u32 = 1;
/// Patch version of the C API.
pub const IC_API_VERSION_PATCH: u32 = 0;

/// Report the version of the library.
///
/// Each pointer may be null, in which case that component is not written.
///
/// # Safety
///
/// Non-null pointers must point to writable `u32` storage.
#[no_mangle]
pub unsafe extern "C" fn ic_api_version(
  major: *mut u32,
  minor: *mut u32,
  patch: *mut u32,
) {
  if !major.is_null() {
    // SAFETY: caller guarantees a valid, writable u32.
    unsafe { *major = IC_API_VERSION_MAJOR };
  }
  if !minor.is_null() {
    // SAFETY: as above.
    unsafe { *minor = IC_API_VERSION_MINOR };
  }
  if !patch.is_null() {
    // SAFETY: as above.
    unsafe { *patch = IC_API_VERSION_PATCH };
  }
}
