/* iClaustron Data API — C header.
 *
 * Copyright (c) 2026 Hopsworks and/or its affiliates.
 * Licensed under the MIT License. See LICENSE in the repository root.
 *
 * PHASE 0 DESIGN ARTEFACT. This file is written by hand from
 * doc/rust/04-api-design.md and is the review document for the API. From
 * Phase 7 on it is generated by cbindgen from crates/ic_capi and checked
 * in; `cargo xtask header` diffs the two.
 *
 * Target: RonDB 26.10 data nodes. Scope of release 0.1: configuration from
 * ndb_mgmd, node membership and failure handling, dictionary, transactions
 * with primary key and unique key operations, interpreted conditions on
 * key operations. Scans, events, DDL and BLOBs are later releases and are
 * only named in the "reserved" section at the end.
 */
#ifndef IC_APID_H
#define IC_APID_H

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

/*
  GENERAL PRINCIPLES ON NAMING AND DATA HIDING
  --------------------------------------------
  All object types are written in capital letters and are opaque: the
  application only ever holds pointers to them and calls functions on
  them. There are no vtables and no struct prefixes to cast; every
  operation is a plain function named ic_<object>_<verb>, e.g.
  ic_apid_conn_read_key(). This keeps the ABI stable and makes the
  library easy to call from any language that can call C.

  A few plain data structures are visible (IC_APID_ERROR, IC_FIELD_SPEC,
  IC_GLOBAL_OPTIONS, IC_READ_KEY_ARGS, IC_WRITE_KEY_ARGS). They are C
  structs with a fixed layout; the *_ARGS and *_OPTIONS structs start
  with their own size so that fields can be appended in later versions
  without breaking callers.

  RETURN CODES
  ------------
  Functions return int: 0 on success, otherwise an error code. Codes
  7000..7999 are iClaustron errors (see ic_err.h), other codes are NDB
  error codes as reported by the data nodes. Every object keeps its last
  error as an IC_APID_ERROR reachable through ic_*_get_error().

  THREADS
  -------
  An IC_APID_GLOBAL is shared by all threads of the process. An
  IC_APID_CONNECTION is owned by exactly one thread and must not be used
  from two threads at the same time. Callbacks run on the thread that
  calls ic_apid_conn_poll() or ic_apid_conn_flush(), never on a library
  thread.
*/

/* ------------------------------------------------------------------ */
/* Version                                                             */
/* ------------------------------------------------------------------ */

#define IC_API_VERSION_MAJOR 0
#define IC_API_VERSION_MINOR 1
#define IC_API_VERSION_PATCH 0

/* Report the version of the linked library. Null pointers are skipped. */
void ic_api_version(uint32_t *major, uint32_t *minor, uint32_t *patch);

/* ------------------------------------------------------------------ */
/* Opaque objects                                                      */
/* ------------------------------------------------------------------ */

typedef struct ic_apid_global IC_APID_GLOBAL;
typedef struct ic_apid_connection IC_APID_CONNECTION;
typedef struct ic_table_def IC_TABLE_DEF;
typedef struct ic_index_def IC_INDEX_DEF;
typedef struct ic_record IC_RECORD;
typedef struct ic_apid_query IC_APID_QUERY;
typedef struct ic_transaction IC_TRANSACTION;
typedef struct ic_transaction_hint IC_TRANSACTION_HINT;
typedef struct ic_where_condition IC_WHERE_CONDITION;
typedef struct ic_conditional_assignment IC_CONDITIONAL_ASSIGNMENT;

/* ------------------------------------------------------------------ */
/* Enumerations (values are part of the ABI: append, never insert)     */
/* ------------------------------------------------------------------ */

/* Field (column) types as defined by RonDB 26.10. Values follow the NDB
   type numbering so that they can be compared with ndb_desc output. */
typedef enum ic_field_type
{
  IC_TYPE_UNDEFINED = 0,
  IC_TYPE_TINYINT = 1,           /* 1 byte signed */
  IC_TYPE_TINYUNSIGNED = 2,
  IC_TYPE_SMALLINT = 3,          /* 2 bytes */
  IC_TYPE_SMALLUNSIGNED = 4,
  IC_TYPE_MEDIUMINT = 5,         /* 3 bytes */
  IC_TYPE_MEDIUMUNSIGNED = 6,
  IC_TYPE_INT = 7,               /* 4 bytes */
  IC_TYPE_UNSIGNED = 8,
  IC_TYPE_BIGINT = 9,            /* 8 bytes */
  IC_TYPE_BIGUNSIGNED = 10,
  IC_TYPE_FLOAT = 11,            /* 4 bytes IEEE */
  IC_TYPE_DOUBLE = 12,           /* 8 bytes IEEE */
  IC_TYPE_OLDDECIMAL = 13,
  IC_TYPE_OLDDECIMALUNSIGNED = 14,
  IC_TYPE_DECIMAL = 15,          /* packed binary, size from precision/scale */
  IC_TYPE_DECIMALUNSIGNED = 16,
  IC_TYPE_CHAR = 17,             /* fixed length, space padded */
  IC_TYPE_VARCHAR = 18,          /* 1 length byte + data */
  IC_TYPE_BINARY = 19,           /* fixed length */
  IC_TYPE_VARBINARY = 20,        /* 1 length byte + data */
  IC_TYPE_DATETIME = 21,         /* 8 bytes */
  IC_TYPE_DATE = 22,             /* 3 bytes */
  IC_TYPE_BLOB = 23,             /* not supported in records (later release) */
  IC_TYPE_TEXT = 24,             /* not supported in records (later release) */
  IC_TYPE_BIT = 25,              /* n bits, stored in ceil(n/32) words */
  IC_TYPE_LONGVARCHAR = 26,      /* 2 length bytes (little endian) + data */
  IC_TYPE_LONGVARBINARY = 27,    /* 2 length bytes (little endian) + data */
  IC_TYPE_TIME = 28,             /* 3 bytes */
  IC_TYPE_YEAR = 29,             /* 1 byte */
  IC_TYPE_TIMESTAMP = 30,        /* 4 bytes */
  IC_TYPE_TIME2 = 31,            /* 3 + fractional bytes */
  IC_TYPE_DATETIME2 = 32,        /* 5 + fractional bytes */
  IC_TYPE_TIMESTAMP2 = 33        /* 4 + fractional bytes */
} IC_FIELD_TYPE;

typedef enum ic_index_type
{
  IC_PRIMARY_KEY = 0,
  IC_UNIQUE_KEY = 1,             /* unique hash index, usable for key queries */
  IC_ORDERED_INDEX = 2           /* usable for range scans (later release) */
} IC_INDEX_TYPE;

/* Commit state of a transaction as seen by the application. */
typedef enum ic_commit_state
{
  IC_TRANS_STARTED = 0,
  IC_COMMIT_REQUESTED = 1,
  IC_ROLLBACK_REQUESTED = 2,
  IC_COMMITTED = 3,
  IC_ROLLED_BACK = 4
} IC_COMMIT_STATE;

/*
  Read key queries have different locking semantics.
  IC_SIMPLE_KEY_READ: take a shared lock, read, release the lock at once.
  IC_KEY_READ: shared lock held until commit or rollback.
  IC_EXCLUSIVE_KEY_READ: exclusive lock held until commit or rollback.
  IC_COMMITTED_KEY_READ: read the latest committed value without locking.
  IC_EXCLUSIVE_KEY_READ_NO_WAIT: as exclusive, but fail instead of waiting
  for a lock held by another transaction (RonDB no-wait flag).
*/
typedef enum ic_read_key_query_type
{
  IC_SIMPLE_KEY_READ = 0,
  IC_KEY_READ = 1,
  IC_EXCLUSIVE_KEY_READ = 2,
  IC_COMMITTED_KEY_READ = 3,
  IC_EXCLUSIVE_KEY_READ_NO_WAIT = 4
} IC_READ_KEY_QUERY_TYPE;

typedef enum ic_write_key_query_type
{
  IC_KEY_UPDATE = 0,             /* row must exist */
  IC_KEY_WRITE = 1,              /* insert or overwrite */
  IC_KEY_INSERT = 2,             /* row must not exist */
  IC_KEY_DELETE = 3
} IC_WRITE_KEY_QUERY_TYPE;

/* What happens to the transaction when this query fails in the data node.
   The default is IC_ABORT_ON_ERROR for writes and IC_IGNORE_ERROR for
   reads; committed reads only allow IC_IGNORE_ERROR. */
typedef enum ic_abort_option
{
  IC_ABORT_DEFAULT = 0,
  IC_ABORT_ON_ERROR = 1,
  IC_IGNORE_ERROR = 2
} IC_ABORT_OPTION;

/* RonDB batch scheduling hint on write operations (TCKEYREQ bits 22/23).
   Safe: the operation does not depend on earlier operations in the same
   batch. Unsafe: it does. None: let the data node decide. */
typedef enum ic_batch_hint
{
  IC_BATCH_NONE = 0,
  IC_BATCH_SAFE = 1,
  IC_BATCH_UNSAFE = 2
} IC_BATCH_HINT;

typedef enum ic_boolean_type
{
  IC_AND = 0,
  IC_OR = 1,
  IC_XOR = 2
} IC_BOOLEAN_TYPE;

typedef enum ic_comparator_type
{
  IC_COND_EQ = 0,
  IC_COND_LT = 1,
  IC_COND_LE = 2,
  IC_COND_GT = 3,
  IC_COND_GE = 4,
  IC_COND_NE = 5
} IC_COMPARATOR_TYPE;

typedef enum ic_calculation_type
{
  IC_PLUS = 0,
  IC_MINUS = 1,
  IC_MULTIPLICATION = 2,
  IC_DIVISION = 3,
  IC_BITWISE_OR = 4,
  IC_BITWISE_AND = 5,
  IC_BITWISE_XOR = 6
} IC_CALCULATION_TYPE;

typedef enum ic_error_severity_level
{
  IC_SEVERITY_NO_ERROR = 0,
  IC_SEVERITY_WARNING = 1,
  IC_SEVERITY_TEMPORARY_ERROR = 2,   /* retry the transaction */
  IC_SEVERITY_ERROR = 3,             /* permanent; fix the request */
  IC_SEVERITY_STOP_ERROR = 4         /* the API instance is unusable */
} IC_ERROR_SEVERITY_LEVEL;

typedef enum ic_error_category
{
  IC_CATEGORY_NO_ERROR = 0,
  IC_CATEGORY_USER_ERROR = 1,        /* e.g. no such row, duplicate key */
  IC_CATEGORY_INTERNAL_ERROR = 2,    /* bug in the API */
  IC_CATEGORY_EXTERNAL_ERROR = 3     /* node failure, overload, timeout */
} IC_ERROR_CATEGORY;

/* ------------------------------------------------------------------ */
/* Plain data structures                                               */
/* ------------------------------------------------------------------ */

/* Error information. Embedded in every object; also usable on the stack
   by the application for calls that report through an out-parameter. */
typedef struct ic_apid_error
{
  int32_t code;                      /* 0 = no error */
  IC_ERROR_CATEGORY category;
  IC_ERROR_SEVERITY_LEVEL severity;
  const char *message;               /* static text, never NULL */
  uint32_t details;                  /* NDB error details word, or 0 */
} IC_APID_ERROR;

/* Marker for a NOT NULL field in IC_FIELD_SPEC.null_byte_offset. */
#define IC_NO_NULL_BIT 0xFFFFFFFFu

/*
  RECORDS
  -------
  A record describes how the fields of a table are laid out in a C struct
  owned by the application. Each field is stored at a byte offset, in the
  same encoding the data node uses, so a read is one copy per field into
  the struct and a write is one copy per field out of it:

    fixed size types         inline at offset, NDB size
    VARCHAR/VARBINARY        1 length byte then data, inline
    LONGVARCHAR/LONGVARBINARY 2 length bytes (little endian) then data
    DECIMAL                  packed binary inline
    BIT(n)                   ceil(n/32) 32-bit words inline
    nullable field           one bit in a null byte; bit set means NULL
    BLOB/TEXT                cannot be part of a record (later release)

  Example:

    struct my_row {
      uint32_t a;          key, INT UNSIGNED NOT NULL
      uint32_t b;          INT UNSIGNED, nullable
      uint8_t  name_len;   VARCHAR(20): length byte followed by data
      char     name[20];
      uint8_t  null_bits;  bit 0: b is NULL
    };
    IC_FIELD_SPEC spec[3] = {
      { ID_A,    offsetof(struct my_row, a),        IC_NO_NULL_BIT, 0 },
      { ID_B,    offsetof(struct my_row, b),
                 offsetof(struct my_row, null_bits), 0 },
      { ID_NAME, offsetof(struct my_row, name_len), IC_NO_NULL_BIT, 0 },
    };
    ic_table_def_create_record(table, spec, 3, sizeof(struct my_row), &rec);

  The application chooses alignment; the API validates that fields do not
  overlap and fit within row_size. ic_table_def_default_record() builds a
  naturally aligned record for callers who do not want to write the struct
  by hand and reports the offsets with ic_record_get_field_layout().

  Fields in a record are numbered by their position in the spec array
  (0..num_fields-1). Field masks passed with queries are bitmaps over these
  positions: bit i set means field i takes part in the query.
*/
typedef struct ic_field_spec
{
  uint32_t field_id;                 /* from ic_table_def_get_field_id() */
  uint32_t offset;                   /* byte offset of the value in the row */
  uint32_t null_byte_offset;         /* null bit byte, or IC_NO_NULL_BIT */
  uint32_t null_bit;                 /* bit number 0..7 within that byte */
} IC_FIELD_SPEC;

/* Options for ic_apid_global_connect(). Zero means "default" for every
   numeric field; NULL means default for every pointer field. */
typedef struct ic_global_options
{
  uint32_t struct_size;              /* sizeof(IC_GLOBAL_OPTIONS) */
  uint32_t node_id;                  /* 0 = let ndb_mgmd allocate */
  uint32_t receive_threads;          /* fixed once connected; default 1 */
  uint32_t heartbeat_interval_ms;    /* default from the cluster config */
  uint32_t connect_timeout_ms;       /* to ndb_mgmd; default 30000 */
  uint32_t max_send_wait_us;         /* adaptive send bound; default 200 */
  uint32_t max_user_threads;         /* connection objects; default 256 */
  const char *bind_address;          /* local address for data node sockets */
  const char *process_name;          /* shown to the cluster; default argv[0] */
} IC_GLOBAL_OPTIONS;

/*
  CALLBACKS
  ---------
  Called from ic_apid_conn_poll()/ic_apid_conn_flush() on the calling
  thread when a query or a commit/rollback completes. `query` is NULL for
  commit and rollback completions. The return value is reserved and must
  be 0.
*/
typedef int (*IC_APID_CALLBACK_FUNC)(IC_APID_CONNECTION *conn,
                                     IC_TRANSACTION *trans,
                                     IC_APID_QUERY *query, /* NULL on commit */
                                     void *user_reference);

/* Arguments to ic_apid_conn_read_key(). */
typedef struct ic_read_key_args
{
  uint32_t struct_size;              /* sizeof(IC_READ_KEY_ARGS) */
  IC_READ_KEY_QUERY_TYPE query_type;
  const void *key_row;               /* row in the key record layout */
  void *attr_row;                    /* attribute row; written on completion */
  const uint8_t *attr_mask;          /* bitmap over attr fields; NULL = all */
  IC_ABORT_OPTION abort_option;
  IC_APID_CALLBACK_FUNC callback;    /* NULL = no callback */
  void *user_reference;
} IC_READ_KEY_ARGS;

/* Arguments to ic_apid_conn_write_key(). For IC_KEY_DELETE attr_row and
   attr_mask are ignored. */
typedef struct ic_write_key_args
{
  uint32_t struct_size;              /* sizeof(IC_WRITE_KEY_ARGS) */
  IC_WRITE_KEY_QUERY_TYPE query_type;
  const void *key_row;
  const void *attr_row;              /* values to write */
  const uint8_t *attr_mask;          /* fields to write; NULL = all non-key */
  IC_ABORT_OPTION abort_option;
  IC_BATCH_HINT batch_hint;
  IC_APID_CALLBACK_FUNC callback;
  void *user_reference;
} IC_WRITE_KEY_ARGS;

/* ------------------------------------------------------------------ */
/* IC_APID_GLOBAL: one per process                                     */
/* ------------------------------------------------------------------ */

/*
  Connects to ndb_mgmd through the connectstring ("host:port,host:port",
  optionally "nodeid=N,host:port"), allocates a node id, fetches the
  configuration, starts the send, receive and heartbeat threads and begins
  connecting to the data nodes. Returns before the data nodes are
  connected; call ic_apid_global_wait_first_node_connect() before using
  a connection. `error` may be NULL.
*/
int ic_apid_global_connect(const char *connectstring,
                           const IC_GLOBAL_OPTIONS *options,
                           IC_APID_GLOBAL **global,
                           IC_APID_ERROR *error);

/* Wait up to wait_ms for at least one data node to be connected and
   started. Returns 0, or IC_ERROR_TIMEOUT. */
int ic_apid_global_wait_first_node_connect(IC_APID_GLOBAL *global,
                                           uint32_t wait_ms);

/* Wait until all data nodes that are alive in the cluster are connected,
   or wait_ms has passed. */
int ic_apid_global_wait_all_nodes_connect(IC_APID_GLOBAL *global,
                                          uint32_t wait_ms);

/* Our own node id in the cluster. */
uint32_t ic_apid_global_get_node_id(IC_APID_GLOBAL *global);

/* Data nodes in the configuration, and whether one is currently up. */
uint32_t ic_apid_global_get_num_data_nodes(IC_APID_GLOBAL *global);
uint32_t ic_apid_global_get_data_node_id(IC_APID_GLOBAL *global,
                                         uint32_t index);
int ic_apid_global_is_node_up(IC_APID_GLOBAL *global, uint32_t node_id);

/* Cooperative shutdown flag shared by all threads of the application. */
int ic_apid_global_get_stop_flag(IC_APID_GLOBAL *global);
void ic_apid_global_set_stop_flag(IC_APID_GLOBAL *global);

/* Number of connection objects currently created. */
uint32_t ic_apid_global_get_num_connections(IC_APID_GLOBAL *global);

/* Last error on the global object. */
const IC_APID_ERROR *ic_apid_global_get_error(IC_APID_GLOBAL *global);

/* Conditions and assignments stored on the global object can be mapped
   into any query on any connection (see the WHERE section). */
int ic_apid_global_create_where_condition(IC_APID_GLOBAL *global,
                                          IC_TABLE_DEF *table_def,
                                          IC_WHERE_CONDITION **cond,
                                          uint32_t *cond_id);
int ic_apid_global_create_conditional_assignment(
    IC_APID_GLOBAL *global,
    IC_TABLE_DEF *table_def,
    IC_CONDITIONAL_ASSIGNMENT **assign,
    uint32_t *assign_id);

/* Disconnect from the cluster, stop all threads, free everything. All
   connections, queries and records created from this global must have
   been freed. */
void ic_apid_global_free(IC_APID_GLOBAL *global);

/* ------------------------------------------------------------------ */
/* IC_APID_CONNECTION: one per application thread                      */
/* ------------------------------------------------------------------ */

/*
  The connection object is the thread's channel to the cluster. All
  queries are defined on it, sent through it and their completions are
  collected from it. It is not thread safe; one thread owns it.

  The normal way to use it is asynchronous:
    1. define queries (ic_apid_conn_read_key / ic_apid_conn_write_key)
    2. ic_apid_conn_send() to hand them to the send threads
    3. do other work
    4. ic_apid_conn_poll() to execute the replies
    5. iterate ic_apid_conn_get_next_executed_query()
  ic_apid_conn_flush() combines 2 and 4 for the simple synchronous case.

  Between ic_apid_conn_send() and completion the key and attribute rows
  of a sent query belong to the API and must not be touched.
*/
int ic_apid_conn_create(IC_APID_GLOBAL *global, IC_APID_CONNECTION **conn);
void ic_apid_conn_free(IC_APID_CONNECTION *conn);
IC_APID_GLOBAL *ic_apid_conn_get_global(IC_APID_CONNECTION *conn);
const IC_APID_ERROR *ic_apid_conn_get_error(IC_APID_CONNECTION *conn);

/*
  Metadata binding. A table definition is fetched from the data nodes
  the first time a table is bound in the process and shared afterwards;
  it is reference counted, so every bind needs an unbind. Names are
  NUL-terminated strings as used in MySQL (database and table name).
*/
int ic_apid_conn_table_bind(IC_APID_CONNECTION *conn,
                            const char *db_name,
                            const char *table_name,
                            IC_TABLE_DEF **table_def);
int ic_apid_conn_index_bind(IC_APID_CONNECTION *conn,
                            const char *db_name,
                            const char *index_name,
                            const char *table_name,
                            IC_INDEX_DEF **index_def);
int ic_apid_conn_table_unbind(IC_APID_CONNECTION *conn,
                              IC_TABLE_DEF *table_def);
int ic_apid_conn_index_unbind(IC_APID_CONNECTION *conn,
                              IC_INDEX_DEF *index_def);

/*
  Transactions. Starting a transaction is a local operation; the
  transaction starts in the data node with the first key query. The hint
  chooses the data node that coordinates the transaction (NULL = round
  robin over live data nodes). Commit and rollback are requests: the
  outcome is known when the callback fires or when the transaction's
  commit state changes after a poll. Once committed or rolled back the
  transaction object is released by the API; the pointer must not be
  used again.
*/
int ic_apid_conn_start_transaction(IC_APID_CONNECTION *conn,
                                   const IC_TRANSACTION_HINT *hint,
                                   IC_TRANSACTION **trans);
int ic_apid_conn_commit_transaction(IC_APID_CONNECTION *conn,
                                    IC_TRANSACTION *trans,
                                    IC_APID_CALLBACK_FUNC callback,
                                    void *user_reference);
int ic_apid_conn_rollback_transaction(IC_APID_CONNECTION *conn,
                                      IC_TRANSACTION *trans,
                                      IC_APID_CALLBACK_FUNC callback,
                                      void *user_reference);

/*
  Key queries. Define a primary key (or, for a query created with
  ic_apid_query_create_unique(), unique key) read or write in the given
  transaction. Nothing is sent until ic_apid_conn_send() or
  ic_apid_conn_flush(). The query object must be idle (freshly created,
  reset, or returned by ic_apid_conn_get_next_executed_query()).
*/
int ic_apid_conn_read_key(IC_APID_CONNECTION *conn,
                          IC_APID_QUERY *query,
                          IC_TRANSACTION *trans,
                          const IC_READ_KEY_ARGS *args);
int ic_apid_conn_write_key(IC_APID_CONNECTION *conn,
                           IC_APID_QUERY *query,
                           IC_TRANSACTION *trans,
                           const IC_WRITE_KEY_ARGS *args);

/*
  Send all queries defined on this connection. With force_send = 0 the
  adaptive algorithm may delay the actual socket write for a short while
  (bounded by IC_GLOBAL_OPTIONS.max_send_wait_us) to batch with other
  threads; with force_send != 0 the write happens now.
*/
int ic_apid_conn_send(IC_APID_CONNECTION *conn, int force_send);

/*
  Wait up to wait_ms for replies, execute them (row data is written into
  the attribute rows, transaction states are updated, callbacks fire).
  Returns 0 if at least one query completed, IC_ERROR_TIMEOUT if nothing
  arrived in time, otherwise an error. After 0, iterate
  ic_apid_conn_get_next_executed_query().
*/
int ic_apid_conn_poll(IC_APID_CONNECTION *conn, uint32_t wait_ms);

/* send + poll. */
int ic_apid_conn_flush(IC_APID_CONNECTION *conn,
                       uint32_t wait_ms,
                       int force_send);

/* Iterate the queries completed by the last poll/flush; NULL when done.
   Each completed query is returned once. */
IC_APID_QUERY *ic_apid_conn_get_next_executed_query(IC_APID_CONNECTION *conn);

/* ------------------------------------------------------------------ */
/* IC_TRANSACTION_HINT                                                 */
/* ------------------------------------------------------------------ */

/* Hint from a key: hashes the distribution key fields found in key_row
   (through key_record) and selects the node holding the primary replica,
   or any replica for read-backup and fully replicated tables. */
int ic_transaction_hint_from_key(IC_TABLE_DEF *table_def,
                                 IC_RECORD *key_record,
                                 const void *key_row,
                                 IC_TRANSACTION_HINT **hint);
/* Hint naming a data node explicitly. */
int ic_transaction_hint_node(IC_APID_GLOBAL *global,
                             uint32_t node_id,
                             IC_TRANSACTION_HINT **hint);
void ic_transaction_hint_free(IC_TRANSACTION_HINT *hint);

/* ------------------------------------------------------------------ */
/* IC_TRANSACTION accessors                                            */
/* ------------------------------------------------------------------ */

uint64_t ic_transaction_get_id(IC_TRANSACTION *trans);
IC_COMMIT_STATE ic_transaction_get_commit_state(IC_TRANSACTION *trans);
uint32_t ic_transaction_get_node_id(IC_TRANSACTION *trans);   /* coordinator */
uint64_t ic_transaction_get_gci(IC_TRANSACTION *trans);       /* after commit */
const IC_APID_ERROR *ic_transaction_get_error(IC_TRANSACTION *trans);

/* ------------------------------------------------------------------ */
/* IC_TABLE_DEF and IC_INDEX_DEF                                       */
/* ------------------------------------------------------------------ */

uint32_t ic_table_def_get_table_id(IC_TABLE_DEF *table_def);
uint32_t ic_table_def_get_table_version(IC_TABLE_DEF *table_def);
uint32_t ic_table_def_get_num_fields(IC_TABLE_DEF *table_def);
int ic_table_def_get_field_id(IC_TABLE_DEF *table_def,
                              const char *field_name,
                              uint32_t *field_id);
const char *ic_table_def_get_field_name(IC_TABLE_DEF *table_def,
                                        uint32_t field_id);
IC_FIELD_TYPE ic_table_def_get_field_type(IC_TABLE_DEF *table_def,
                                          uint32_t field_id);
/* Size in bytes of the field as stored in a record (including length
   bytes for variable sized types). */
uint32_t ic_table_def_get_field_size(IC_TABLE_DEF *table_def,
                                     uint32_t field_id);
/* Precision and scale for DECIMAL; precision holds the fractional second
   digits for TIME2/DATETIME2/TIMESTAMP2; bits for BIT. */
uint32_t ic_table_def_get_field_precision(IC_TABLE_DEF *table_def,
                                          uint32_t field_id);
uint32_t ic_table_def_get_field_scale(IC_TABLE_DEF *table_def,
                                      uint32_t field_id);
uint32_t ic_table_def_get_field_charset(IC_TABLE_DEF *table_def,
                                        uint32_t field_id);
int ic_table_def_is_field_nullable(IC_TABLE_DEF *table_def,
                                   uint32_t field_id);
int ic_table_def_is_field_key(IC_TABLE_DEF *table_def, uint32_t field_id);
int ic_table_def_is_field_distribution_key(IC_TABLE_DEF *table_def,
                                           uint32_t field_id);
int ic_table_def_is_field_autoincrement(IC_TABLE_DEF *table_def,
                                        uint32_t field_id);

/* Primary key fields in key order. */
uint32_t ic_table_def_get_num_key_fields(IC_TABLE_DEF *table_def);
uint32_t ic_table_def_get_key_field_id(IC_TABLE_DEF *table_def,
                                       uint32_t key_order);

/* Table properties relevant to node selection. */
int ic_table_def_is_read_backup(IC_TABLE_DEF *table_def);
int ic_table_def_is_fully_replicated(IC_TABLE_DEF *table_def);
uint32_t ic_table_def_get_num_partitions(IC_TABLE_DEF *table_def);

/* Records over this table (see the RECORDS section). */
int ic_table_def_create_record(IC_TABLE_DEF *table_def,
                               const IC_FIELD_SPEC *spec,
                               uint32_t num_fields,
                               uint32_t row_size,
                               IC_RECORD **record);
/* A naturally aligned record over the given fields (all fields if
   field_ids is NULL); ask ic_record_get_field_layout() for the offsets. */
int ic_table_def_default_record(IC_TABLE_DEF *table_def,
                                const uint32_t *field_ids,
                                uint32_t num_fields,
                                IC_RECORD **record);

/* Index definitions. */
uint32_t ic_index_def_get_index_id(IC_INDEX_DEF *index_def);
IC_INDEX_TYPE ic_index_def_get_index_type(IC_INDEX_DEF *index_def);
IC_TABLE_DEF *ic_index_def_get_table_def(IC_INDEX_DEF *index_def);
uint32_t ic_index_def_get_num_key_fields(IC_INDEX_DEF *index_def);
/* Field ids refer to the base table's fields. */
uint32_t ic_index_def_get_key_field_id(IC_INDEX_DEF *index_def,
                                       uint32_t key_order);
/* A key record over the index key fields, for unique key queries. */
int ic_index_def_create_record(IC_INDEX_DEF *index_def,
                               const IC_FIELD_SPEC *spec,
                               uint32_t num_fields,
                               uint32_t row_size,
                               IC_RECORD **record);

/* ------------------------------------------------------------------ */
/* IC_RECORD                                                           */
/* ------------------------------------------------------------------ */

uint32_t ic_record_get_num_fields(IC_RECORD *record);
uint32_t ic_record_get_row_size(IC_RECORD *record);
/* Layout of one field, by record position (0..num_fields-1). */
int ic_record_get_field_layout(IC_RECORD *record,
                               uint32_t position,
                               uint32_t *field_id,
                               uint32_t *offset,
                               uint32_t *null_byte_offset,
                               uint32_t *null_bit);
/* Record position of a table field id, or IC_ERROR_NO_SUCH_FIELD. */
int ic_record_get_position(IC_RECORD *record,
                           uint32_t field_id,
                           uint32_t *position);
/* Helpers to test and set the NULL bit of a field in a row. */
int ic_record_is_null(IC_RECORD *record, const void *row, uint32_t position);
void ic_record_set_null(IC_RECORD *record, void *row, uint32_t position,
                        int is_null);
void ic_record_free(IC_RECORD *record);

/* ------------------------------------------------------------------ */
/* IC_APID_QUERY                                                       */
/* ------------------------------------------------------------------ */

/*
  A query object is defined once and reused many times. It ties a table
  (or unique index) to a key record and an attribute record. The rows
  themselves are passed with each call in the *_ARGS struct, so the same
  query object can be used with different row buffers.

  Completion handling: after a poll, a completed query is either handled
  in its callback or fetched with ic_apid_conn_get_next_executed_query().
  ic_apid_query_is_failed() tells quickly whether anything went wrong;
  ic_apid_query_get_error() has the details. A completed query is idle
  again and can be used for the next call without ic_apid_query_reset();
  reset is only needed to drop conditions and assignments that were not
  marked as kept.
*/
int ic_apid_query_create(IC_APID_GLOBAL *global,
                         IC_TABLE_DEF *table_def,
                         IC_RECORD *key_record,
                         IC_RECORD *attr_record,
                         IC_APID_QUERY **query);
int ic_apid_query_create_unique(IC_APID_GLOBAL *global,
                                IC_INDEX_DEF *index_def,
                                IC_RECORD *key_record,
                                IC_RECORD *attr_record,
                                IC_APID_QUERY **query);
void ic_apid_query_free(IC_APID_QUERY *query);
int ic_apid_query_reset(IC_APID_QUERY *query);

int ic_apid_query_is_failed(IC_APID_QUERY *query);
const IC_APID_ERROR *ic_apid_query_get_error(IC_APID_QUERY *query);
void *ic_apid_query_get_user_reference(IC_APID_QUERY *query);
IC_TRANSACTION *ic_apid_query_get_transaction(IC_APID_QUERY *query);
IC_TABLE_DEF *ic_apid_query_get_table_def(IC_APID_QUERY *query);
/* For reads: number of attribute bytes received (0 for a row not found
   under IC_IGNORE_ERROR, with error code 626). */
uint32_t ic_apid_query_get_result_length(IC_APID_QUERY *query);

/*
  WHERE conditions on a query. One condition per query; it is evaluated in
  the data node before the read or write. Either create one on the query
  or map one created on the global object by its id. A condition created
  on the query is released when the query completes unless
  ic_apid_query_keep_where() was called for this execution.
*/
int ic_apid_query_create_where_condition(IC_APID_QUERY *query,
                                         IC_WHERE_CONDITION **cond);
int ic_apid_query_map_where_condition(IC_APID_QUERY *query,
                                      uint32_t global_cond_id);
void ic_apid_query_keep_where(IC_APID_QUERY *query);

/*
  Conditional assignments on an update query. First declare how many, then
  create or map each by position. Assignments are executed in order and
  each sees the results of the previous ones.
*/
int ic_apid_query_create_conditional_assignments(IC_APID_QUERY *query,
                                                 uint32_t num_assignments);
int ic_apid_query_create_conditional_assignment(
    IC_APID_QUERY *query,
    uint32_t position,
    IC_CONDITIONAL_ASSIGNMENT **assign);
int ic_apid_query_map_conditional_assignment(IC_APID_QUERY *query,
                                             uint32_t position,
                                             uint32_t global_assign_id);
void ic_apid_query_keep_conditional_assignments(IC_APID_QUERY *query);

/* ------------------------------------------------------------------ */
/* IC_WHERE_CONDITION                                                  */
/* ------------------------------------------------------------------ */

/*
  A WHERE condition is built by walking the condition tree left-deep and
  emitting one call per node. Boolean nodes (AND, OR, XOR) open two
  subroutines and return their ids; comparisons end a subroutine; field
  and constant reads and calculations put values into typed memory
  addresses handed out by the API. Subroutine 0 is the top level.

  WHERE a = 1 AND b < (c + 3) becomes:

    ic_where_define_boolean(cond, 0, &left, &right, IC_AND);
    ic_where_read_field_into_memory(cond, left, &m_a, ID_A);
    ic_where_read_const_into_memory(cond, left, &m_1, &one, 4, IC_TYPE_INT);
    ic_where_define_condition(cond, left, m_a, m_1, IC_COND_EQ);
    ic_where_read_field_into_memory(cond, right, &m_b, ID_B);
    ic_where_read_field_into_memory(cond, right, &m_c, ID_C);
    ic_where_read_const_into_memory(cond, right, &m_3, &three, 4, IC_TYPE_INT);
    ic_where_define_calculation(cond, right, &m_sum, m_c, m_3, IC_PLUS);
    ic_where_define_condition(cond, right, m_b, m_sum, IC_COND_LT);
    ic_where_evaluate(cond);

  If the top node is a comparison, start with ic_where_define_first(); if
  it is NOT, with ic_where_define_not(). ic_where_evaluate() compiles the
  program for the RonDB 26.10 interpreter and reports errors such as type
  mismatches or IC_ERROR_CONDITION_TOO_COMPLEX (more than 8 live values
  in release 0.1). LIKE runs in the data node; a regular expression is
  evaluated by the API after the row has been read.
*/
int ic_where_define_boolean(IC_WHERE_CONDITION *cond,
                            uint32_t current_subroutine_id,
                            uint32_t *left_subroutine_id,
                            uint32_t *right_subroutine_id,
                            IC_BOOLEAN_TYPE boolean_type);
int ic_where_define_condition(IC_WHERE_CONDITION *cond,
                              uint32_t current_subroutine_id,
                              uint32_t left_memory_address,
                              uint32_t right_memory_address,
                              IC_COMPARATOR_TYPE comp_type);
int ic_where_read_field_into_memory(IC_WHERE_CONDITION *cond,
                                    uint32_t current_subroutine_id,
                                    uint32_t *memory_address,
                                    uint32_t field_id);
int ic_where_read_const_into_memory(IC_WHERE_CONDITION *cond,
                                    uint32_t current_subroutine_id,
                                    uint32_t *memory_address,
                                    const void *const_ptr,
                                    uint32_t const_len,
                                    IC_FIELD_TYPE const_type);
int ic_where_define_calculation(IC_WHERE_CONDITION *cond,
                                uint32_t current_subroutine_id,
                                uint32_t *returned_memory_address,
                                uint32_t left_memory_address,
                                uint32_t right_memory_address,
                                IC_CALCULATION_TYPE calc_type);
int ic_where_define_not(IC_WHERE_CONDITION *cond,
                        uint32_t current_subroutine_id,
                        uint32_t *subroutine_id);
int ic_where_define_first(IC_WHERE_CONDITION *cond,
                          uint32_t current_subroutine_id,
                          uint32_t *subroutine_id);
/* LIKE / regular expression on a field, or on the byte range
   [start_pos, end_pos) of it when use_full_field is 0. The pattern is a
   constant loaded into memory first. */
int ic_where_define_like(IC_WHERE_CONDITION *cond,
                         uint32_t current_subroutine_id,
                         uint32_t field_id,
                         int use_full_field,
                         uint32_t start_pos,
                         uint32_t end_pos,
                         uint32_t pattern_memory_address);
int ic_where_define_regexp(IC_WHERE_CONDITION *cond,
                           uint32_t current_subroutine_id,
                           uint32_t field_id,
                           int use_full_field,
                           uint32_t start_pos,
                           uint32_t end_pos,
                           uint32_t pattern_memory_address);
int ic_where_evaluate(IC_WHERE_CONDITION *cond);
const IC_APID_ERROR *ic_where_get_error(IC_WHERE_CONDITION *cond);
void ic_where_free(IC_WHERE_CONDITION *cond);

/* ------------------------------------------------------------------ */
/* IC_CONDITIONAL_ASSIGNMENT                                           */
/* ------------------------------------------------------------------ */

/*
  An assignment computes a value from fields and constants and writes it
  into one field; the last call is always ic_cond_assign_write_field().
  a = a * (b + 1) becomes:

    ic_cond_assign_read_field_into_memory(as, &m_a, ID_A);
    ic_cond_assign_read_field_into_memory(as, &m_b, ID_B);
    ic_cond_assign_read_const_into_memory(as, &m_1, &one, 4, IC_TYPE_INT);
    ic_cond_assign_define_calculation(as, &m_sum, m_b, m_1, IC_PLUS);
    ic_cond_assign_define_calculation(as, &m_res, m_a, m_sum,
                                      IC_MULTIPLICATION);
    ic_cond_assign_write_field(as, m_res, ID_A);

  Optionally the assignment is guarded by a WHERE condition created with
  ic_cond_assign_create_condition() or mapped from the global object.
*/
int ic_cond_assign_create_condition(IC_CONDITIONAL_ASSIGNMENT *assign,
                                    IC_WHERE_CONDITION **cond);
int ic_cond_assign_map_condition(IC_CONDITIONAL_ASSIGNMENT *assign,
                                 uint32_t global_cond_id);
int ic_cond_assign_read_field_into_memory(IC_CONDITIONAL_ASSIGNMENT *assign,
                                          uint32_t *memory_address,
                                          uint32_t field_id);
int ic_cond_assign_read_const_into_memory(IC_CONDITIONAL_ASSIGNMENT *assign,
                                          uint32_t *memory_address,
                                          const void *const_ptr,
                                          uint32_t const_len,
                                          IC_FIELD_TYPE const_type);
int ic_cond_assign_define_calculation(IC_CONDITIONAL_ASSIGNMENT *assign,
                                      uint32_t *returned_memory_address,
                                      uint32_t left_memory_address,
                                      uint32_t right_memory_address,
                                      IC_CALCULATION_TYPE calc_type);
int ic_cond_assign_write_field(IC_CONDITIONAL_ASSIGNMENT *assign,
                               uint32_t memory_address,
                               uint32_t field_id);
const IC_APID_ERROR *
ic_cond_assign_get_error(IC_CONDITIONAL_ASSIGNMENT *assign);
void ic_cond_assign_free(IC_CONDITIONAL_ASSIGNMENT *assign);

/* ------------------------------------------------------------------ */
/* IC_APID_ERROR helpers                                               */
/* ------------------------------------------------------------------ */

void ic_apid_error_init(IC_APID_ERROR *error);        /* set to "no error" */
const char *ic_apid_error_message(int32_t code);     /* text for any code */
IC_ERROR_CATEGORY ic_apid_error_category(int32_t code);
IC_ERROR_SEVERITY_LEVEL ic_apid_error_severity(int32_t code);

/* ------------------------------------------------------------------ */
/* Program scaffolding (optional)                                      */
/* ------------------------------------------------------------------ */

/*
  For programs that want the iClaustron thread-pool driven structure:
  ic_start_program parses the standard command line options
  (--ndb-connectstring, --node-id, --num-threads, --debug-level, ...),
  ic_start_apid_program connects the global object, ic_run_apid_program
  starts num_threads user threads each with its own connection and runs
  the given function in them until all return, ic_stop_apid_program
  frees everything. Applications are free to ignore this section and
  use ic_apid_global_connect() directly.
*/
typedef struct ic_thread_state IC_THREAD_STATE;
typedef int (*IC_RUN_APID_THREAD_FUNC)(IC_APID_CONNECTION *conn,
                                       IC_THREAD_STATE *thread_state);

int ic_start_program(int argc, char **argv, const char *program_name,
                     IC_GLOBAL_OPTIONS *options,
                     const char **connectstring,
                     uint32_t *num_threads);
int ic_start_apid_program(const char *connectstring,
                          const IC_GLOBAL_OPTIONS *options,
                          IC_APID_GLOBAL **global,
                          IC_APID_ERROR *error);
int ic_run_apid_program(IC_APID_GLOBAL *global,
                        uint32_t num_threads,
                        IC_RUN_APID_THREAD_FUNC thread_func);
void ic_stop_apid_program(IC_APID_GLOBAL *global);

/* Thread state helpers usable from IC_RUN_APID_THREAD_FUNC. */
uint32_t ic_thread_state_get_id(IC_THREAD_STATE *thread_state);
int ic_thread_state_get_stop_flag(IC_THREAD_STATE *thread_state);

/* ------------------------------------------------------------------ */
/* Reserved for later releases (names fixed, not declared here)        */
/* ------------------------------------------------------------------ */
/*
  0.2  IC_RANGE_CONDITION, ic_apid_conn_scan(), IC_SCAN_ARGS,
       ic_apid_query_scan_next_row(), ic_apid_query_scan_close(),
       ic_apid_query_set_partition_id(), takeover write from a scanned row.
  0.3  IC_METADATA_TRANSACTION, IC_ALTER_TABLE, events, autoincrement,
       TLS options in IC_GLOBAL_OPTIONS.
  later IC_BLOB_HANDLE, IC_ALTER_TABLESPACE, SPJ, aggregation.
*/

#ifdef __cplusplus
}
#endif
#endif /* IC_APID_H */
