[package]
name = "ic_node_ping"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Connect to every data node of a RonDB cluster and exchange heartbeats"

[lints]
workspace = true

[dependencies]
ic_port.workspace = true
ic_util.workspace = true
ic_apic.workspace = true
ic_apid.workspace = true
