#ifndef IC_ERR_H
#define IC_ERR_H

struct ic_config_err
{
  guint32 err_num;
  guint32 line_number;
};
typedef struct ic_config_err IC_CONFIG_ERROR;

#define IC_ERROR_CONFIG_LINE_TOO_LONG 7000
#define IC_ERROR_CONFIG_BRACKET 7001
#define IC_ERROR_CONFIG_INCORRECT_GROUP_ID 7002
#define IC_ERROR_CONFIG_IMPROPER_KEY_VALUE 7003
#define IC_ERROR_CONFIG_NO_SUCH_SECTION 7004
#define IC_ERROR_MEM_ALLOC 7005
#define IC_ERROR_NO_SECTION_DEFINED_YET 7006
#define IC_ERROR_NO_SUCH_CONFIG_KEY 7007
#define IC_ERROR_DEFAULT_VALUE_FOR_MANDATORY 7008
#define IC_ERROR_CORRECT_CONFIG_IN_WRONG_SECTION 7009
#define IC_ERROR_NO_NODES_FOUND 7010
#define IC_ERROR_WRONG_CONFIG_NUMBER 7011
#define IC_ERROR_NO_BOOLEAN_VALUE 7012
#define IC_ERROR_CONFIG_VALUE_OUT_OF_BOUNDS 7013
#define IC_ERROR_NO_SERVER_NAME 7014
#define IC_ERROR_NO_SERVER_PORT 7015
#define IC_ERROR_GETADDRINFO 7016
#define IC_ERROR_ILLEGAL_SERVER_PORT 7017
#define IC_ERROR_DIFFERENT_IP_VERSIONS 7018
#define IC_ERROR_ILLEGAL_CLIENT_PORT 7019
#endif
